[env]
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit SSD1306@^2.5.13

[env:esp32dev_ota]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DENABLE_OTA=1
upload_protocol = espota
upload_port = 192.168.0.200
upload_flags =
    -a
    ${sysenv.OTA_PASSWORD}

[env:esp32dev_ota_uart]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DENABLE_OTA=1
upload_protocol = esptool
upload_port = /dev/ttyUSB0

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0

[env:mic_probe]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DMIC_PROBE=1
upload_port = /dev/ttyUSB0

[env:amp_probe]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DAMP_PROBE=1
upload_port = /dev/ttyUSB0